/**
 * Embeds JPEG assets as base64 data URIs — guaranteed to load offline.
 * Run: npm run images
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const assetsDir = join(root, 'src/assets/images');
const outFile = join(root, 'src/data/image-data.js');

if (!existsSync(join(assetsDir, 'hero.jpg'))) {
  execSync('node scripts/generate-images.mjs', { cwd: root, stdio: 'inherit' });
}

const files = {
  hero: 'hero.jpg',
  ctaBg: 'cta-bg.jpg',
  bouquet01: 'bouquet-01.jpg',
  bouquet02: 'bouquet-02.jpg',
  bouquet03: 'bouquet-03.jpg',
  bouquet04: 'bouquet-04.jpg',
  bouquet05: 'bouquet-05.jpg',
  bouquet06: 'bouquet-06.jpg',
  bouquet07: 'bouquet-07.jpg',
  bouquet08: 'bouquet-08.jpg',
  composition01: 'composition-01.jpg',
  composition02: 'composition-02.jpg',
  single01: 'single-01.jpg',
  balloons01: 'balloons-01.jpg',
  potted01: 'potted-01.jpg',
  toy01: 'toy-01.jpg',
  toy02: 'toy-02.jpg',
  souvenir01: 'souvenir-01.jpg',
  souvenir02: 'souvenir-02.jpg',
  painting01: 'painting-01.jpg',
  painting02: 'painting-02.jpg',
};

const encoded = {};
for (const [key, filename] of Object.entries(files)) {
  const buf = readFileSync(join(assetsDir, filename));
  if (buf.length < 500) {
    throw new Error(`Image too small (corrupt?): ${filename} (${buf.length} bytes)`);
  }
  encoded[key] = `data:image/jpeg;base64,${buf.toString('base64')}`;
  console.log(`✓ ${filename} → ${(buf.length / 1024).toFixed(1)} KB`);
}

const output = `/* Auto-generated by scripts/embed-images.mjs — do not edit */
${Object.entries(encoded).map(([k, v]) => `export const ${k} = "${v}";`).join('\n')}
`;

writeFileSync(outFile, output);
console.log(`\nWritten ${outFile}`);
